### ISSUE TITLE
'Format only on manual save' mode

### ISSUE THREAD

**Issue by bitfield** [mauve/vscode-terraform#112]
I'm having a little trouble getting `vscode-terraform` to work the way I want. My point of comparison is `vscode-go`; with that extension, files are formatted every time you save them manually, but not on auto-save.

In Terraform, though, with `editor.formatOnSave` enabled, the file is reformatted on an auto-save. This is really disconcerting when you open a block prior to typing a line of code, pause to think about it, and suddenly the block you were in disappears.

Is there any combination of settings which will run the formatter only when I manually save the file, even if I have auto-save enabled? Or is this a feature of `vscode-go` which doesn't exist in `vscode-terraform`?

(I don't want to have to format the document manually, per the suggestion to #60. It's easy to forget to do that and check in a busted file. You can't do that if it's formatted on save.)

**Comment by mauve** [comment]
you are right, I have been meaning to kill the format on auto-save feature for quite some time but the _backlash_ was relatively large last time I tried, but just the last couple of days I have been getting several bug reports about breaking other functionality.

in the next release it goes away :)

thanks for using my plugin, and thanks for finally giving me a good reason to kill this feature I do really do not like :)

I am currently preparing a new release, I hope to have this fixed in the same one, hopefully released over the weekend.
