### ISSUE TITLE
cannot install language server behind auth proxy

### ISSUE THREAD

**Issue by kinwolfqc** [mauve/vscode-terraform#238]
I simply cannot enable the language server for 0.12.  When it tries to download the setup it fails and I see in the output that the proxy blocked it because the authentication is required.  Proxy setting is set in vscode(everything else work fine to download and isntall extensions)  

I read a ton of threads, set the HTTPS_PROXY and HTTP_PROXY just to be sure.  I've tried every tricks in the book that I saw, nothing works.

Is there any solution to install this extension correctly when behind a proxy that required authentication?

**Comment by springfan** [comment]
I'm facing the same issue. It prints:

`Failed starting language server. Error: HttpError: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Access Denied (authentication_failed)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
`

**Comment by springfan** [comment]
Setting "http.proxy" to my proxy url in vscode settings.json solved my problem.

**Comment by kinwolfqc** [comment]
That solved it, thanks!
